name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "0 18 * * *"  # Runs daily at 18:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v4

      - uses: yoshi389111/github-profile-3d-contrib@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
          SETTING_JSON: conf/github-profile-3d-contrib.json

      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          
          # Stash any unstaged changes before pulling
          git stash -u
      
          # Pull with rebase
          git pull --rebase origin main
          
          # Apply stashed changes after pulling
          git stash pop || true
      
          # Add and commit changes if any
          git add -A .
          if git diff-index --quiet HEAD; then
            echo "No changes to commit."
          else
            git commit -m "generated"
            git push origin main
          fi
