# name: GitHub-Profile-3D-Contrib

# on:
#   schedule: # 03:00 JST == 18:00 UTC
#     - cron: "0 18 * * *"
#   workflow_dispatch:

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     name: generate-github-profile-3d-contrib
#     steps:
#       - uses: actions/checkout@v4

#       - uses: yoshi389111/github-profile-3d-contrib@latest
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#           USERNAME: ${{ github.repository_owner }}
#           SETTING_JSON: conf/github-profile-3d-contrib.json

#       - name: Commit & Push
#         run: |
#           git config user.name github-actions
#           git config user.email github-actions@github.com
          
#           # Add all changes
#           git add -A .
          
#           # Commit changes if any
#           if git commit -m "generated"; then
#             git push
#           else
#             echo "No changes to commit."
